version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/presto-ui/src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "fast-uri"
    labels:
      - "dependencies"
