connector.name=clickhouse
clickhouse.connection-url=jdbc:clickhouse://52.116.206.37:8443?ssl=true&sslmode=strict&sslrootcert=/Users/nishithakbhaskaran/Documents/clickhouse-cert.cert
clickhouse.connection-user=TM_LAKEHOUSE_ENGINE_USER_1
clickhouse.connection-password=qRVnsDTa
clickhouse.map-string-as-varchar=true
clickhouse.allow-drop-table=true
case-sensitive-name-matching=true